
# 제약 조건 
/*
 * 
 * 	NOT NULL : NULL 금지
 *  UNIQUE : 중복값입력 금지(NULL은가능)
 *  PRIMARY KEY : NOT NULL + UNIQUE
 *  FOREIGN KEY : 다른 테이블 컬럼을 조회함
 *  CHECK : 조건으로 설정된 값만 허용
 *
 * */
 
CREATE TABLE MEMBER(
	NUM INT NOT NULL PRIMARY KEY,			
    NAME VARCHAR(20) NOT NULL,
    SCORE INT
);

INSERT MEMBER(SCORE) 	  VALUES(100); 				    # ERROR : NOT NULL 데이터가 NULL값이다.
INSERT MEMBER(NAME,SCORE) VALUES('제임스고슬링',100);		# ERROR : NOT NULL 데이터가 NULL값이다.
INSERT MEMBER(NUM,NAME)   VALUES(1000,'데니스리치');
INSERT MEMBER 		      VALUES(1001,'버너스리',100);
INSERT MEMBER 			  VALUES(1001,'앨런튜링',100);    # ERROR : PRIMARY KEY가 중복되어있다.
INSERT MEMBER 			  VALUES(1002,'앨런튜링',100);
SELECT * FROM MEMBER;
DROP TABLE MEMBER;


CREATE TABLE MEMBER(
	NUM INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL
);

INSERT MEMBER(NAME) VALUES('MYSQL');
INSERT MEMBER(NAME) VALUES('MSSQL');
INSERT MEMBER(NAME) VALUES('ORACLE');
INSERT MEMBER(NAME) VALUES('POSTGRESQL');

SELECT * FROM MEMBER;
DROP TABLE MEMBER;









